version: "3.2"

services:

  mongo:

    container_name: docker_mongo
    image: mongo:6.0.3
    restart: always
    volumes:
      - ./db:/data/db
      # - /etc/timezone:/etc/timezone:ro
      # - /etc/localtime:/etc/localtime:ro
    ports:
      - ${MONGO_PORT}:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
    env_file:
      - ../../.env

networks:
  default:
    external:
      name: api_network
